# Synap extension = original extensions
extension.mapping.mp4=m4v,mov,m4a,mpg,mpeg
extension.mapping.mp3=aac,mpg,mpeg,vob
extension.mapping.m4v=m4a
extension.mapping.bzip=bz,bz2,tbz
extension.mapping.xml=dtd,svg,ovf,tfw
extension.mapping.icon=ico,flv
extension.mapping.jpg=jpeg,jfif
extension.mapping.tar=ova
extension.mapping.number=numbers
extension.mapping.page=pages
extension.mapping.sxi=odp
extension.mapping.sxc=ods
extension.mapping.sxw=odt
extension.mapping.mht=eml
extension.mapping.gz=tgz,tar
extension.mapping.html=htm
extension.mapping.msg=oft
extension.mapping.asf=wmv,wma
extension.mapping.doc=dot
extension.mapping.docx=docm
extension.mapping.ppt=pot,pps
extension.mapping.xlsx=xltx
extension.mapping.iso=emf
extension.mapping.hwp=hwt
extension.mapping.qt=mov
extension.mapping.c=cpp
extension.mapping.webp=jpg,jpeg
extension.mapping.exe=dll

# (alz > a00, a01...)
extension.split-ext.alz=a\\d{2}
extension.split-ext.rar=r\\d{2}
extension.split-ext.zip=z\\d{2}
extension.split-ext.7z=\\d{3}

#
extension.split-name.rar=.*\\.part\\d+\\.rar$
extension.split-name.7z=.*\\.7z\\.\\d{3}$
extension.split-name.zip=.*\\.zip\\.\\d{3}$