USE AEGISAI;

CREATE TABLE IF NOT EXISTS PROCESSING_QUEUE
(
	MSGID         VARCHAR(64) NOT NULL COMMENT '메시지 아이디',
	TASK_TYPE     VARCHAR(50) NULL COMMENT '처리 종류 (예: OCR, ML_ANALYSIS 등)',
	STATUS        ENUM ('PENDING','RUNNING','DONE','FAILED') DEFAULT 'PENDING',
	DATA          JSON        NULL COMMENT '처리 데이터 (Message)',
	ERROR_MESSAGE TEXT        NULL COMMENT 'Error Message',
	RUN_AT        DATETIME    NOT NULL                       DEFAULT CURRENT_TIMESTAMP COMMENT '실행 시간',
	CREATE_DT     DATETIME                                   DEFAULT CURRENT_TIMESTAMP COMMENT '등록 시간',
	PRIMARY KEY (MSGID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;